### PR TITLE
Add docker

### PR DESCRIPTION
**Pull request by fxfactorial**
Make it super easy for anyone to run openFace with a prebuilt container with docker.

### CODE REVIEW

**Comment by elahia** [comment]
@fxfactorial  Thank you Edgar so much for your effort,  i'm new to docker too, 
so it's what i done and the result... i didn't go farther to avoid any mistakes,
So would you please what shoud i do now? (Please see the attache
screenshot from 2018-06-02 08 57 38
)

**Comment by TadasBaltrusaitis** [comment]
Make sure you are in develop branch of OpenFace for this. I will be merging the docker image creation with the master branch later today.

**Comment by elahia** [comment]
@fxfactorial Thank you so much for such a great help, i could run your image and test it, the result was: starting tracking,

so now how can I try for a live face tracking by my webcam?

**Comment by elahia** [comment]
Yes, i think so,
but i need to install openface to use it online!
Let me ask another question!
Only thing that i want is running openface on Linux. then i will use the
provided csv file! what is the easiest way?  already i done it on
windosebut
its around one week that i stuck in it for ubuntu!


On Sat, Jun 2, 2018 at 5:36 PM, Edgar Aroutiounian <notifications@github.com

**Comment by elahia** [comment]
@fxfactorial  @TadasBaltrusaitis  
 Hello Dears,
My deadline is really close and the base of my methodology is based on using openface on ubuntu...
So please help me to find it out how to use it (the installation caused to strange errors and proposed docker image is not able to proceed with webcam..). without openface i cannot do anything... 


Thanks in advance...

**Pull request merged**
