### PR TITLE
Fully modified to be compatible with OpenCV 4.0.0

### PR DESCRIPTION
**Pull request by jiapei100**
Now, OpenFace is built upon OpenCV 4.0.0 ....

### CODE REVIEW

**Comment by TadasBaltrusaitis** [comment]
Hi,

Thanks. I will hold on this for a bit (I'm waiting for OpenCV 4.0.0 to become a stable release that is cross-platform). Further, it seems like it failed the Continuous Integration tests and is not building on Windows.

**Comment by Kaspik** [comment]
Hey! OpenCV 4.0 is out and stable. OpenCV2 is out on CocoaPods for iOS - but because of OpenFace is not compatible yet, we can't update. How does it look here?

**Comment by TadasBaltrusaitis** [comment]
Thanks for letting me know that OpenCV 4.0 is out. I was waiting for it to become stable to start the transition of OpenFace to it. I don't know how easy it will be, but I will start the investigation soon.

**Comment by Kaspik** [comment]
We have OpenFace as lib inside project, so I did the migration manually already (it was like 20 mins).

**Comment by TadasBaltrusaitis** [comment]
While migrating in one OS might be easy, I need to make sure it can build easily and works on Windows/Ubuntu/OSX, so will probably take a bit more than 20 minutes :)

**Comment by cindyloo** [comment]
hows the upgrade to OpenCV 4.x going? tx

**Comment by TadasBaltrusaitis** [comment]
It is almost complete, you can have a look at the following branch - https://github.com/TadasBaltrusaitis/OpenFace/tree/feature/opencv4 for a work in progress

**Comment by TadasBaltrusaitis** [comment]
OpenFace 4.1 is now the default version used in OpenFace

**Pull request closed without merging**
