### PR TITLE
Qt5 cross platform gui

### PR DESCRIPTION
**Pull request by fxfactorial**
Builds on OSX with 

build_qt_gui.sh

and run the binary `openface-cross-platform-gui` from within the `build/bin` directory.
Adapt as needed for Windows or Linux (I might add another commit to build on linux as well). 

screen shot 2018-05-23 at 10 51 36 am

### CODE REVIEW

**Comment by fxfactorial** [comment]
Build failing on travis is not relevant because its just missing QT5 but including qt5 on each build would be wasting time, as qt5 installation is non-trivial time

**Comment by TadasBaltrusaitis** [comment]
Hi, the ability to pass Travis CI is very important, as this allows to identify compilation issues on non Windows machines, without the build passing I cannot include the changes to OpenFace.

**Comment by fxfactorial** [comment]
Can't you install an OSX for travis CI? I can have that building probably

**Comment by TadasBaltrusaitis** [comment]
Ideally I would like CI to work on both Ubuntu and OSX, to make sure that the code is properly cross-platform. However, I have been having some issues with OSX builds that I would like to fix soon.

**Comment by fxfactorial** [comment]
Okay, I'll try to add to both OS X and Ubuntu. Did you consider that update i did for the openblas, at least to get linux to compile.

**Comment by TadasBaltrusaitis** [comment]
Your suggested change to CMake results in the following error in travis on osx:

`  By not providing "FindOpenBLAS.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenBLAS",
  but CMake did not find one.
  Could not find a package configuration file provided by "OpenBLAS" with any
  of the following names:
    OpenBLASConfig.cmake
    openblas-config.cmake`

**Comment by TadasBaltrusaitis** [comment]
I believe, I managed to fix the travis CI to be able to build both OSX and Ubuntu versions, I will be integrating it into master shortly, but the current version on develop can successfully build both.

**Comment by fxfactorial** [comment]
Awesome, I will rebase and add some more UI that I have since wrote for this

**Comment by TadasBaltrusaitis** [comment]
What OS is this on? It might be an issue with OS X and OpenBLAS

**Comment by fxfactorial** [comment]
yes, OS X.

**Comment by TadasBaltrusaitis** [comment]
I think your code ends up linking to OpenBLAS rather than Accelerate, as now OpenFace does not set number of threads for OpenBLAS to use when the OS is OSX.

Can you try using the following - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Mac-installation#blas-performance

I wonder if there is a better way to deal with this issue though.

**Comment by fxfactorial** [comment]
Okay, I will try in a few minutes but also, what about the other PR I had which was a cmake ifelse on openblas? That at least would compile & work for linux/osx

**Comment by TadasBaltrusaitis** [comment]
I was not able to make it run on travis CI, it could not find OpenBLAS, resulting in:
`By not providing "FindOpenBLAS.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "OpenBLAS", but CMake did not find one. Could not find a package configuration file provided by "OpenBLAS" with any of the following names: OpenBLASConfig.cmake openblas-config.cmake`

**Comment by fxfactorial** [comment]
Any way for me to replicate this environment short of just running commands in Travis directly ?

**Comment by fxfactorial** [comment]
fwiw: 
screen shot 2018-05-29 at 3 58 11 pm

**Comment by TadasBaltrusaitis** [comment]
Travis uses the following environment - https://docs.travis-ci.com/user/reference/osx/, I'm using the default one, but it is possible to specify other ones as well.

**Comment by tatsujb** [comment]
@chiragraman is the gui not yet available for cross platform? I followed these instructions here  : https://askubuntu.com/a/1132991/307184 (yes they are mine) but at the end, to test you in the linux install guide : https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation you only suggest command line solutions for running it.

**Comment by fxfactorial** [comment]
seems no one cares about this

**Pull request closed without merging**
