### PR TITLE
Add missing header ConcurrentQueue.h

### PR DESCRIPTION
**Pull request by sziraqui**
Continuation of #723 against develop branch

### CODE REVIEW

**Comment by sziraqui** [comment]
Travis CI could not download the models with wget

**Comment by sziraqui** [comment]
@TadasBaltrusaitis How do I rerun the build on Travis?

**Comment by TadasBaltrusaitis** [comment]
I just restarted the build and it passed. This change will make it into master in a couple of weeks when I'm doing a new release.

**Comment by sziraqui** [comment]
There are few more things in cmakelists that needs improvement. One should be able to compile openface as shared library. I using it as shared lib right now. Should it be made default or as an option? I have the modified cmake file locally, I can raise a PR for it but it will work only when its dependencies are also compiled as shared lib. Just few minor changes in travis will help us acheive it. What are your thoughts?

**Comment by TadasBaltrusaitis** [comment]
I agree that a shared library compilation would be a good idea for OpenFace, setting it as a default options sounds good, looking forward to the PR.

**Pull request merged**
